name: Build Image using Containerfile.
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: fedora-toolbox-alex
        tags: latest 35 ${{ github.ref_name }}
        containerfiles: |
          ./Containerfile

    - name: Push Image
      id: push-to-github
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/amanning9
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
